# your essential settings
title: Y-E-S
email: mail@y-e-s.org
locales:
  about: About
  details: Details
  download: Download
  email: Your email address
  about: About
  setup: Setup
  subscribe: Subscribe
  thanks: Thank you!
  display_mode:
    list: ▤
    cover: ⧉

# setup
collections:
  - releases

sass:
  sass_dir: assets/styles
  style: compressed

markdown: kramdown
